name: Mirror to Repo B

on:
  push:
    branches:
      - main   # change if your branch is different

jobs:
  mirror:
    # Run ONLY in Repo A, never in private_portfolio
    if: github.repository == 'Baloshi69/AlbaloshiTech_portfolio'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo A
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Configure Git
        run: |
          git config user.name "Baloshi69"
          git config user.email "github-actions@users.noreply.github.com"

      - name: Push to Repo B
        env:
          MIRROR_TOKEN: ${{ secrets.MIRROR_TOKEN }}
        run: |
          git remote add mirror https://Baloshi69:${MIRROR_TOKEN}@github.com/Baloshi69/private_portfolio.git
          git push mirror main --force
